#CI项目
name: TestBuild

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      CONFIG:
        default: 'Cudy_Tr3000'
        required: true
        type: choice
        options:
          - Cudy_Tr3000
      SOURCE:
        default: 'openwrt/openwrt'
        required: true
        type: choice
        options:
          - openwrt/openwrt
      BRANCH:
        default: 'develop'
        required: true
        type: string
      PACKAGE:
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: true
        required: true
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [Cudy_Tr3000]
        SOURCE: [openwrt/openwrt]
        BRANCH: [openwrt-24.10]

    uses: ./.github/workflows/OpenWrt-CI.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: Openwrt
      #默认地址
      WRT_IP: 172.16.0.1
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #默认密码，修改无用
      WRT_PW: 无
      #默认WIFI名称
      WRT_SSID: Openwrt
      #默认WIFI密码
      WRT_WORD: 12345678
      #测试参数
      WRT_TEST: ${{inputs.TEST}}