#CI项目
name: WRT-ALL

#CI计划
on:
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:
    # inputs:
    #   PACKAGE:
    #     description: '手动调整插件包，多个请用\n符号隔开。'
    #     required: false
    #     type: string

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [Cudy_Tr3000]
        SOURCE: [openwrt/openwrt]
        BRANCH: [openwrt-24.10]

    uses: ./.github/workflows/openwrt-ci.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: Openwrt
      #默认WIFI名称
      WRT_SSID: Openwrt
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 172.16.0.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      # #插件调整
      # WRT_PACKAGE: ${{inputs.PACKAGE}}